export enum UkraineLocationEnum {
  LVIV = 'Lviv',
  ZAKARPATTIA = 'Zakarpattia',
  KYIV = 'Kyiv',
  RIVNE = 'Rivne',
  AUTONOMOUS_REPUBLIC_OF_CRIMEA = 'Autonomous Republic of Crimea',
  VINNYTSIA = 'Vinnytsia',
  VOLYN = 'Volyn',
  DNIPROPETROVSK = 'Dnipropetrovsk',
  DONETSK = 'Donetsk',
  ZHYTOMYR = 'Zhytomyr',
  ZAPORIZHIA = 'Zaporizhia',
  IVANO_FRANKIVSK = 'Ivano-Frankivsk',
  KYIV_CITY = 'Kyiv City',
  KIROVOHRAD = 'Kirovohrad',
  LUGANSK = 'Luhansk',
  MYKOLAIV = 'Mykolaiv',
  ODESA = 'Odesa',
  POLTAVA = 'Poltava',
  SUMY = 'Sumy',
  TERNOPIL = 'Ternopil',
  KHARKIV = 'Kharkiv',
  KHMELNYTSKYI = 'Khmelnytskyi',
  CHERKASY = 'Cherkasy',
  CHERNIVTSI = 'Chernivtsi',
  CHERNIHIV = 'Chernihiv',
 }